### PR TITLE
Provide a template for new PRs

### PR DESCRIPTION
**Pull request by olethanh**
As discussed, providing these informations on each PR should improve review and code quality

### CODE REVIEW

**Comment by hoh** [comment]
What about reusing the template from https://github.com/aleph-im/aleph-client/pull/244/files instead of the generic one ?

**Comment by olethanh** [comment]
It's not generic, I Just opened all the Pr at the same time. Will update this one.

**Comment by Psycojoker** [comment]
Is there any reason not to merge this one?

**Review by hoh — APPROVED** [review]

**Comment by hoh** [comment]
I restarted the test that failed.

**Pull request merged**
