### PR TITLE
Refactor VMType path

### PR DESCRIPTION
**Pull request by nesitor**
Problem: Class VMType are coupled to orchestration path.

Solution: Decouple VMType class to be outside orchestrator path.

### CODE REVIEW

**Comment by hoh** [comment]
Would it not make sense to move this into aleph-message instead ?

**Comment by nesitor** [comment]
> Would it not make sense to move this into aleph-message instead ?

Can be, but for the moment we need to merge this refactor just to advance on next steps. Later we can move it easily to aleph-message repository.

**Review by MHHukiewitz — APPROVED** [review]
LGTM

**Comment by MHHukiewitz** [comment]
Merging for now, we will do bigger refactorings after we fixed it all. No sense in refactoring buggy code.

**Pull request merged**
